### ISSUE TITLE
Dev's want to play locally before investing $$$ on servers

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#123]
We should promote local dev in the README file and ensure that's the "quick" setup

https://github.com/gitevents/core#how-to-run-gitevents-locally--as-a-developer

**Comment by PatrickHeneise** [comment]
In early discussions we agreed on gitevents being a polished product that can be used by non-tech organisers, so the quick setup for end users has more priority, no?

**Comment by iancrowther** [comment]
right now, were ramping up dev's, not end users.

**Comment by martinheidegger** [comment]
Would a docker-image solve that issue?

**Comment by iancrowther** [comment]
@martinheidegger its in a docker image already

the goal of this issue is around getting a dev started in <5 mins

**Comment by iancrowther** [comment]
not all have docker eperience

**Comment by PatrickHeneise** [comment]
@martinheidegger @iancrowther we already have the docker image (for production) https://quay.io/repository/gitevents/gitevents. I think with the CLI we're closing in on the issue of on-boarding. Maybe we can produce a video that explains shortly what gitevents does and how it works, that might make most sense?

**Comment by iancrowther** [comment]
that would be cool

**Comment by mike182uk** [comment]
I have create https://github.com/gitevents/core/issues/161 to capture the outcome of this.

As for getting users setup quickly, i believe https://github.com/gitevents/core/issues/148 is probably the best solution for this.
