### ISSUE TITLE
refactor - create or use a module that setus up the milestones

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#127]
this should be a testable module really

**Comment by PatrickHeneise** [comment]
that's https://github.com/gitevents/core/blob/master/lib/milestone.js, no?

**Comment by iancrowther** [comment]
cant npm install that though

**Comment by PatrickHeneise** [comment]
no, it's a core module. Stuff that's required to run gitevents (web hook, milestones, events, talks) should not be npm modules.

**Comment by iancrowther** [comment]
Ok

**Comment by PatrickHeneise** [comment]
Was just thinking if the functionality makes sense to outsource, but since it's just using `github` npm module which is tested, there's really no need.

**Comment by iancrowther** [comment]
so I would like to create a module to "setup milestones" anyway, so that UG's that dont want to use gitevents fully, still have a utility belt of helpers.  non essential though, nice to have

**Comment by PatrickHeneise** [comment]
alright. So far I see the milestone setup pretty essential (given the event id is stored in the milestone description and so on). If there's a group who doesn't want to use milestones, we can re-open the issue I guess.

**Comment by iancrowther** [comment]
Is closed right? No stress
