### ISSUE TITLE
Git ignore credential files

### ISSUE THREAD

**Issue by mike182uk** [gitevents/core#132]
The credential files should be ignored from the repo to prevent these from being accidentally committed

**Comment by PatrickHeneise** [comment]
all files with `.credentials.js` are ignored already https://github.com/gitevents/core/blob/master/.gitignore

**Comment by mike182uk** [comment]
Ah, mine wasn't being ignored because i excluded the `.js` from the filename when i created it (`github.credentials` instead of `github.credentials.js`)
