### ISSUE TITLE
nodegit

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#134]
@PatrickHeneise have you seen this?

http://www.nodegit.org/

interesting take on setup?

**Comment by PatrickHeneise** [comment]
looks very interesting indeed.

**Comment by PatrickHeneise** [comment]
would it make sense to use it in gitevents, maybe for the json and .md files?

**Comment by iancrowther** [comment]
not sure yet, I just wanted to bring to your attention for when we are making architectual decitions

right tool, right job etc

**Comment by PatrickHeneise** [comment]
:+1:
