### ISSUE TITLE
update readme.md / configs

### ISSUE THREAD

**Issue by PatrickHeneise** [gitevents/core#138]
Most complete config.js currently is: https://gist.github.com/PatrickHeneise/9fa500564b1b809a0894

References, readme etc. need to be updated.

**Comment by iancrowther** [comment]
from @martinheidegger

"had to read the docs a 2nd time. Means: I didn’t get what its about the first time around…."

**Comment by iancrowther** [comment]
so the readme still needs some love

**Comment by iancrowther** [comment]
@martinheidegger - "The setup just seems a bit twisted."
@iancrowther - "agreed, run it locally is how were going to re-order it"

**Comment by iancrowther** [comment]
Is this tool a supporter (i.e. I maintain the events on meetup and it supports me on doing so) or is it a controller (i.e. I maintain the events through gitevents and it automatically submits changes to meetup)

**Comment by PatrickHeneise** [comment]
I think it's a controller, you use GitHub Issues as planning HQ and changes/updates are automatically synced across enabled plugins (=platforms)?
