### ISSUE TITLE
data sync

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#146]
does the platform sync changes from meetup to gitevents?

**Comment by iancrowther** [comment]
you can manually update meetup without any impact?
however… if you update the issue.. it’ll blow your meetup changes!!

**Comment by PatrickHeneise** [comment]
You can update meetup, nothing happens with the rest. You can update gitevents and updates should be synced across other platforms (gitevents-meetup doesn't do updates yet, working on it)

**Comment by mike182uk** [comment]
Closing - looks like patrick has answered.
