### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by PatrickHeneise** [gitevents/core#215]
This app worked great for a while at BarcelonaJS, NodeJS Barcelona and the London Node User Group, but is outdated and there are now great tools like [Probot](https://github.com/probot/probot) to simplify the whole app.

The idea was and is still quite simple: Any meet up can be represented by a GitHub Organisation or single repo, events are managed through issues and milestones.

If someone is interested to bring this project back to live and use it for their own meet up, I'm happy to transfer ownership.

/cc @iancrowther @nomad3k @mike182uk

**Comment by iancrowther** [comment]
im happy to take ownership, who's still using it?

**Comment by PatrickHeneise** [comment]
I don't think anyone is using this at the moment.

A rewrite with [Probot](https://github.com/probot) could make this useful again.

**Comment by PatrickHeneise** [comment]
Great! You're already owner, so you can just continue from here. 🎉
