### ISSUE TITLE
create Twitter module

### ISSUE THREAD

**Issue by PatrickHeneise** [gitevents/core#6]
Send automatic tweets when talks are approved/assigned to events.

**Comment by iancrowther** [comment]
tweet speakers talk titles in the run up to the event

**Comment by iancrowther** [comment]
thank speakers after event with link to slides if exist

**Comment by h02e56** [comment]
i'm gonna work with this

**Comment by h02e56** [comment]
i've implemented the send tweet and also added a formatter. Maybe i should leave as is,  when we really know what wil be sended to this module, do the final work in the formatter. Meanwhile I could work in other stuff

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by iancrowther** [comment]
@h02e56 can you add a list to the readme for integrations and link to your repo? ty

**Comment by h02e56** [comment]
i ve done this changes.(maybe something missing)
Should I go to gitevents branch and make a pull?
I have to work on data comming from core to give it format

**Comment by ifraixedes** [comment]
@h02e56 please add the link to the repo as @iancrowther suggested.
Thanks

**Comment by h02e56** [comment]
I had formatted  readme incorrectly. done

**Comment by iancrowther** [comment]
im a bit puzzled? did you add a link to the readme?

**Comment by h02e56** [comment]
lol, true, fixed
later i will comment some doubts about what i will receive

**Comment by h02e56** [comment]
About twitter i'm formatting the event as for example: 
"New @bcnjs talk! 01/21/2015 @testUser2 Development environments using fig... meetup.com "
I really don't know if i exeed the max chars it will send 2 tweets, i gess so , but i like the idea to just send one x talk or job. I'm having some problems with description formatting..

Some thoughts:
Should we automate some type or remember tweet until the date of event?
About say thanks to the speaker and link to the slides. What in github will trigger it?(new issue?)
What twitter module will receive?

I decided to start with this module without seeing that was fase 3, maybe i should had tried another one...my mistake..if u think taht maybe we should wait just tell me

Cheeers , "bona nit i tapat". :)

**Comment by iancrowther** [comment]
- only send one tweet
'New @bcnjs talk!' this is redundant as its posted to the @bcnjs twitter account.  there's a few chars back.  can you make the description a link to the talk (issue or website)? that way it can be elipsed.

**Comment by iancrowther** [comment]
remember tweet until the date of event? - yes, maybe add a label to say tweeted so it only posts once, ever

**Comment by iancrowther** [comment]
"About say thanks to the speaker and link to the slides"

can we use event date + 1? can you access event date?  i wish the milestones api would arrive!

**Comment by iancrowther** [comment]
I think this is a key feature so should continue :-) doing great!

**Comment by h02e56** [comment]
👍

**Comment by h02e56** [comment]
Hi
I liked the idea of : "make the description a link to the talk (issue or website)"
I have been trying but twitter api gives me some problems or I'm missing something.
As far i understand  we should use twitter entities:
I have used "'twitter-text" to create them and also I ve used bitly api to get some t.co "twitter style " urls becouse I  thought that twitter entities require them. 
I will ask you if someone has some clue about it

Thank you!

**Comment by ifraixedes** [comment]
I don't remember exactly, because I used twitter api with node with [twit](https://github.com/ttezel/twit), but I don't remember that I had issues with URLs, nonetheless I was more getting tweets than sending.

What happens when you send a tweet with an URL?

**Comment by h02e56** [comment]
If we send a url it will creat a t.co style url
As Ian suggested could be a good idea to write the event description text and used as a link to the event page(meetup or whatever). To achieve this, looking at documentation looks like we should use "twitter entities" . As far i understand this entities could be used to get info from tweets an also to send messages .
To send messages i'm using "node-twitter" that looks very similar than yours(twit)
I'm also using 'twitter-text' to generate the entities. Tying this it didn't work and i thought that maybe we should send a already created shorten url(t.co style), so I create them, but anyway it doesn't work as expected.

Maybe i'm complicating myself, and the api is not very handy, and maybe we should take another option. if you want to take look:
https://github.com/h02e56/gitevents-twitter/blob/dev/formatter.js
what right now are sending is something like this: New talk: flE8Jhttp://bit.ly/1Dq9pmg

If we send a standard url we will get a t.co shorten url if url is too long. Maybe we should go this way and later improved 

Gràcies Ivan

**Comment by ifraixedes** [comment]
I don't get you, what are the benefits to use the entities? You said that is working without them, then I think that for the first release would be fine and after, and we'll improve for the next ones. For my point of view is more important to have the actions which work and after add the fancy things in future iterations.

I will try to pull your code in the weekend and run it and try to see the issues to have a better understanding.

Gràcies you for the collaboration.

**Comment by h02e56** [comment]
Yep,
As far I understood to make a tweet like this: "new talk: mvc in depth" where text "mvc in depth" is a link to the event page we should use entities, but maybe i'm wrong. Anyway I agree with you about make module work and after add some fancy stuff.
I ve pushed a basic setup for tweet jobs and talks in my branch master
Tweet results on https://twitter.com/patstest. There are random chars to avoid that twitter consider it repeated
Is missed the greetings to the speaker

**Comment by ifraixedes** [comment]
cool, thanks.

**Comment by iancrowther** [comment]
@PatrickHeneise pls add a reason for closing
