### ISSUE TITLE
org chart

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#70]
who should I contact if I want to get involved? who can point me to issues that are appropriate for my level of expertise?

**Comment by iancrowther** [comment]
lets just run this https://www.npmjs.com/package/contributor

**Comment by PatrickHeneise** [comment]
:+1:

**Comment by mike182uk** [comment]
This looks to have been done as part of https://github.com/gitevents/core/commit/971aa349bb6043a668b86a448ce19b0c69f8099f
