### ISSUE TITLE
should we setup a newsletter?

### ISSUE THREAD

**Issue by iancrowther** [gitevents/core#74]
hack day info, paired programming days etc

**Comment by PatrickHeneise** [comment]
Maybe, yeah. Mail chimp?

**Comment by iancrowther** [comment]
Seems sensible, I bought all the domains so I'll setup a mailchimp account under contact@gitevents.  I'll see if I can share admin rights via my domain registrar

**Comment by iancrowther** [comment]
Although I'm in ownership etc, I'm big on decentralisation so always try to make assets owned by the org as much as possible

**Comment by PatrickHeneise** [comment]
Sounds good. No need for admin rights/share as long as everything points to github.

**Comment by iancrowther** [comment]
Ok

**Comment by mike182uk** [comment]
Closing - not sure in the value of this being an open issue. Seems like more of an organisational issue rather than something related to the core `gitevents`
