### ISSUE TITLE
Pair-Programming

### ISSUE THREAD

**Issue by PatrickHeneise** [GitEvents/core#78]
Comment `beginner`, `advanced` or `expert` here to state your level if you're interested in a pair programming session to solve some gitevents issues. We'll use [AtomPair](https://atom.io/packages/atom-pair) for the session.

**Comment by h02e56** [comment]
yep,
i would like. advanced

**Comment by sgimeno** [comment]
I'm in. Advanced?

**Comment by h02e56** [comment]
hola Sergi,
Let's do some pair if you want. We could start maybe doing some refact at webhook.
I'm working this weekend, what  about do some pair next week? could u contact me by email? I'm not atom user but suppose i will handle it
Let me know
Salut!

**Comment by iancrowther** [comment]
@PatrickHeneise is this still valid?

**Comment by PatrickHeneise** [comment]
Valid yes; used no.
