### ISSUE TITLE
Process "Special Events"

### ISSUE THREAD

**Issue by PatrickHeneise** [gitevents/core#9]
Every once in a while there's a special thing going on ... be it BeachJS, BeerJS, whatever. Those events usually don't have talks, but a time, location, organiser, whatever.
- JSON has to be defined for special events (check for example [BeachJS](https://github.com/barcelona-js/barcelonajs.org/blob/master/contents/2014.json#L174)).
- Label has to be specified
- Webhook processing has to be implemented.

**Comment by iancrowther** [comment]
moved to a feedback repo

**Comment by PatrickHeneise** [comment]
Let's keep it here ;)
